# version: '3'

# services:
#   app:
#     build: 
#       context: ""
#     ports:
#       - "9000"

version: '3'

services:
  application:
    build: .
    # image: "load balancing server" 
    ports:
      - "61616:61616"
